package:
  name: "madina"
  version: "0.0.5"

source:
  git_rev: v1.3.1
  git_url: https://github.com/City-Form-Lab/madina

requirements:
  host:
    - python
    - setuptools
  build:
    python
  run:
    - python
    - geopandas
    - pydeck
    - pyogrio
    - Rtree
  about:
    home: https://github.com/City-Form-Lab/madina
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: "A library to simplify creating workflows for urban planning research. Tools to work with geometry, networks and geo-processing"


